### PR TITLE
progress on schedule module over weekend

### PR DESCRIPTION
**Pull request by jyaaan**

### CODE REVIEW

**Review by victormejia — CHANGES_REQUESTED** [review]
In general, `schedule.js` should contain what is needed for a `Schedule` object. Put any test harnesses in a different file, maybe `test-schedule.js` that you can use to test out your `Schedule`.

**Comment by jyaaan** [comment]
Makes it cleaner! I moved the testSchedule declaration and test over to its own file.

**Review by victormejia — CHANGES_REQUESTED** [review]
Small comment, your Promise/callback architecture could use some improvements. Generally, the use of Promises eliminates the need to pass around callbacks; it's supposed to be a cleaner way of doing things.

Leverage promises, and do any necessary "callback" functionality when promises are resolved.

**Comment by jyaaan** [comment]
Made the changes and verified that it works.

**Review by victormejia — CHANGES_REQUESTED** [review]
looks good!

**Review by victormejia — APPROVED** [review]
whoops...

**Pull request merged**
